INSERT INTO airlines (`Id`, `Airline`, `Abbreviation`, `Country`) VALUES ("1", "United Airlines", "UAL", "USA");
INSERT INTO airlines (`Id`, `Airline`, `Abbreviation`, `Country`) VALUES ("2", "US Airways", "USAir", "USA");
INSERT INTO airlines (`Id`, `Airline`, `Abbreviation`, `Country`) VALUES ("3", "Delta Airlines", "Delta", "USA");
INSERT INTO airlines (`Id`, `Airline`, `Abbreviation`, `Country`) VALUES ("4", "Southwest Airlines", "Southwest", "USA");
INSERT INTO airlines (`Id`, `Airline`, `Abbreviation`, `Country`) VALUES ("5", "American Airlines", "American", "USA");
INSERT INTO airlines (`Id`, `Airline`, `Abbreviation`, `Country`) VALUES ("6", "Northwest Airlines", "Northwest", "USA");
INSERT INTO airlines (`Id`, `Airline`, `Abbreviation`, `Country`) VALUES ("7", "Continental Airlines", "Continental", "USA");
INSERT INTO airlines (`Id`, `Airline`, `Abbreviation`, `Country`) VALUES ("8", "JetBlue Airways", "JetBlue", "USA");
INSERT INTO airlines (`Id`, `Airline`, `Abbreviation`, `Country`) VALUES ("9", "Frontier Airlines", "Frontier", "USA");
INSERT INTO airlines (`Id`, `Airline`, `Abbreviation`, `Country`) VALUES ("10", "AirTran Airways", "AirTran", "USA");
INSERT INTO airlines (`Id`, `Airline`, `Abbreviation`, `Country`) VALUES ("11", "Allegiant Air", "Allegiant", "USA");
INSERT INTO airlines (`Id`, `Airline`, `Abbreviation`, `Country`) VALUES ("12", "Virgin America", "Virgin", "USA");

INSERT INTO airports (`City`, `AirportCode`, `AirportName`, `Country`, `CountryAbbrev`) VALUES ("Aberdeen", "APG", "Phillips AAF", "United States", "US");
INSERT INTO airports (`City`, `AirportCode`, `AirportName`, `Country`, `CountryAbbrev`) VALUES ("Aberdeen", "ABR", "Municipal", "United States", "US");
INSERT INTO airports (`City`, `AirportCode`, `AirportName`, `Country`, `CountryAbbrev`) VALUES ("Abilene", "DYS", "Dyess AFB", "United States", "US");
INSERT INTO airports (`City`, `AirportCode`, `AirportName`, `Country`, `CountryAbbrev`) VALUES ("Abilene", "ABI", "Municipal", "United States", "US");
INSERT INTO airports (`City`, `AirportCode`, `AirportName`, `Country`, `CountryAbbrev`) VALUES ("Abingdon", "VJI", "Virginia Highlands", "United States", "US");
INSERT INTO airports (`City`, `AirportCode`, `AirportName`, `Country`, `CountryAbbrev`) VALUES ("Ada", "ADT", "Ada", "United States", "US");
INSERT INTO airports (`City`, `AirportCode`, `AirportName`, `Country`, `CountryAbbrev`) VALUES ("Adak Island", "ADK", "Adak Island Ns", "United States", "US");
INSERT INTO airports (`City`, `AirportCode`, `AirportName`, `Country`, `CountryAbbrev`) VALUES ("Adrian", "ADG", "Lenawee County", "United States", "US");
INSERT INTO airports (`City`, `AirportCode`, `AirportName`, `Country`, `CountryAbbrev`) VALUES ("Afton", "AFO", "Municipal", "United States", "US");
INSERT INTO airports (`City`, `AirportCode`, `AirportName`, `Country`, `CountryAbbrev`) VALUES ("Aiken", "AIK", "Municipal", "United States", "US");
INSERT INTO airports (`City`, `AirportCode`, `AirportName`, `Country`, `CountryAbbrev`) VALUES ("Ainsworth", "ANW", "Ainsworth", "United States", "US");
INSERT INTO airports (`City`, `AirportCode`, `AirportName`, `Country`, `CountryAbbrev`) VALUES ("Akhiok", "AKK", "Akhiok SPB", "United States", "US");
INSERT INTO airports (`City`, `AirportCode`, `AirportName`, `Country`, `CountryAbbrev`) VALUES ("Akiachak", "KKI", "Spb", "United States", "US");
INSERT INTO airports (`City`, `AirportCode`, `AirportName`, `Country`, `CountryAbbrev`) VALUES ("Akiak", "AKI", "Akiak", "United States", "US");
INSERT INTO airports (`City`, `AirportCode`, `AirportName`, `Country`, `CountryAbbrev`) VALUES ("Akron CO", "AKO", "Colorado Plains Regional Airport", "United States", "US");
INSERT INTO airports (`City`, `AirportCode`, `AirportName`, `Country`, `CountryAbbrev`) VALUES ("Akron/Canton OH", "CAK", "Akron/canton Regional", "United States", "US");
INSERT INTO airports (`City`, `AirportCode`, `AirportName`, `Country`, `CountryAbbrev`) VALUES ("Akron/Canton", "AKC", "Fulton International", "United States", "US");